name: genai_app
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - expat=2.6.4
  - libffi=3.4.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.12.8
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - asyncio==3.4.3
      - attrs==24.3.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - cachetools==5.5.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - docstring-parser==0.16
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - google-api-core==2.24.0
      - google-auth==2.37.0
      - google-cloud-aiplatform==1.77.0
      - google-cloud-bigquery==3.27.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.14.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-genai==0.5.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - grpc-google-iam-v1==0.14.0
      - grpcio==1.69.0
      - grpcio-status==1.69.0
      - idna==3.10
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mistune==3.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==2.2.1
      - packaging==24.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pickleshare==0.7.5
      - pillow==11.1.0
      - pipreqs==0.5.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.50
      - proto-plus==1.25.0
      - protobuf==5.29.3
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - python-dateutil==2.9.0.post0
      - pyzmq==26.2.0
      - referencing==0.36.1
      - requests==2.32.3
      - rpds-py==0.22.3
      - rsa==4.9
      - shapely==2.0.6
      - six==1.17.0
      - sounddevice==0.5.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - tinycss2==1.4.0
      - tornado==6.4.2
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websockets==14.1
      - yarg==0.1.9
